# https://cloud.google.com/appengine/docs/standard/python/config/appref

runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest
